### ISSUE TITLE
Communication channels/Project Language?

### ISSUE THREAD

**Issue by margau** [Freifunk-IoT/freifunk-iot-concept#6]
Should we use FFS-Mailinglist, or create our own Mailinglist on freifunk-iot.de?
Main project language English or German? Any opinions?

**Comment by adnidor** [comment]
Considering all the existing issues and documentation is in English, I'd say we keep it.

Do we need a ML? Personally I'm a fan of IRC.
Using the FFS-ML would create spam for a lot of the subscribers, I'd exclude that option

**Comment by margau** [comment]
I would say a ML is more "long term" for important decisions - maybe both?

**Comment by margau** [comment]
Maybe Matrix instead of IRC?

**Comment by adnidor** [comment]
It is possible to use IRC channels via matrix, the opposite is afaik not. 

I "created" the channel #freifunk-iot on hackint, joining is possible via irc client, xmpp client and matrix, see https://www.hackint.org/servers

**Comment by margau** [comment]
Created Hackint-Channel, maybe Mailinglist if project is growing.
